/*
Source code generated by Brave Browser Leo AI
and modified by me
*/
#include <X11/Xlib.h>
#include <X11/Xutil.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include"../include/CGO/CImage.h"
#include<limits.h>
int main(int argc,char*argv[]){
    // --- Setup ---
    Display *display = XOpenDisplay(NULL);
    struct RetrieveDataFromJpegImage_return jpeg=RetrieveDataFromJpegImage("/usr/share/backgrounds/lorikeet.jpg");
    if (!display) {
        fprintf(stderr, "Cannot open display\n");
        return 1;
    }

    int screen    = XDefaultScreen(display);
    Window root   = XRootWindow(display, screen);
    Visual *visual = XDefaultVisual(display, screen);
    int depth     = XDefaultDepth(display, screen);
    // --- Create window ---
    Window window = XCreateSimpleWindow(
        display, root,
        0, 0,        // x, y position
        jpeg.r0, jpeg.r1,   // size
        1,               // border width
        0xff0000,
        0xff00ff
    );

    XSelectInput(display, window, ExposureMask | KeyPressMask);
    XMapWindow(display, window);
    // --- Create Pixmap and GC ---
    Pixmap pixmap=XCreatePixmapFromBitmapData(
        display,
        window,
        jpeg.r2,
        jpeg.r0,
        jpeg.r1,
        0,
        0,
        depth
    );
    GC gc = XCreateGC(display, window, 0, NULL);
    XSetStandardProperties(display,window,"coso","cji",pixmap,argv,argc,NULL);
    // --- Event loop ---
    XEvent event;
    while (1) {
        XNextEvent(display, &event);
        if(event.type==Expose){
            XCopyArea(display,pixmap,window,gc,0,0,jpeg.r0,jpeg.r1,0,0);
        }

        if (event.type == KeyPress) {
            break;
        }
    }
    CleanImageData(jpeg.r2);
    XFreePixmap(display, pixmap);
    XFreeGC(display, gc);
    XDestroyWindow(display, window);
    XCloseDisplay(display);

    return 0;
}